Models/CupType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TRPTools.Models
{
    public class CupType
    {
        public int CupTypeID { get; set; }
        public string CupTypeDesc { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace TRPTools.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Glitter.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TRPTools.Models
{
    public class Glitter
    {
        public int GlitterID { get; set; }

        public string GlitterName { get; set; }
    }
}

Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TRPTools.Models
{
    public class Order
    {
        public User UserID { get; set; }

        public int OrderID { get; set; }

        public IList<CupType> CupType { get; set; }

        public IList<Glitter> Glitter { get; set; }


    }
}

Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TRPTools.Models
{
    public class User
    {
        [Required]
        public string Username { get; set; }

        [Required]
        public string Password { get;  set; }

        [Required]
        public string Verify { get; set; }
        [Required]
        public string Email { get; set; }

        public int UserID { get; set; }

        public IList<Order> Orders { get; set; }



    }
}

ViewModels/AddOrderViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using TRPTools.Models;

namespace TRPTools.ViewModels
{
    public class AddOrderViewModel
    {
        [Required]
        public List<SelectListItem> CupType { get; set; }

        public List<SelectListItem> Glitter { get; set; }

        public AddOrderViewModel(IEnumerable<CupType> cupTypes)
        {

            CupType = new List<SelectListItem>();
            foreach (var type in cupTypes)
            {
                CupType.Add(new SelectListItem
                {
                    Value = type.CupTypeID.ToString(),
                    Text = type.CupTypeDesc
                });
            }

        }

        public AddOrderViewModel(IEnumerable<Glitter> glitters)
        {

            Glitter = new List<SelectListItem>();
            foreach (var type in glitters)
            {
                Glitter.Add(new SelectListItem
                {
                    Value = type.GlitterID.ToString(),
                    Text = type.GlitterName
                });
            }

        }
    }
}

ViewModels/SignUpViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TRPTools.ViewModels
{
    public class SignUpViewModel
    {
        [Required]
        public string Username { get; set; }

        [Required]
        public string Password { get; set; }

        [Required]
        public string Verify { get; set; }
        [Required]
        public string Email { get; set; }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TRPTools.Models;

namespace TRPTools.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TRPTools.Models;
using TRPTools.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TRPTools.Controllers
{
    public class OrderController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }



        [HttpPost]
        public IActionResult Add(AddOrderViewModel vm)
        {
            if (ModelState.IsValid)
            {
                Order newUser = new Order
                {
                    //User = Where (u => u.UserID == AddOrderViewModel.UserID)   *** Not sure that's the right query for that 
                    //CupType = vm.CupType,
                    //Glitter = vm.Glitter
                };
                return Redirect("/Hello/Index");
            }
            return View(vm);
        }
    }
}

Controllers/SignUpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TRPTools.Models;
using TRPTools.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TRPTools.Controllers
{
    public class SignUpController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Add()
        {
            SignUpViewModel vm = new SignUpViewModel();
            return View(vm);
        }

        [HttpPost]
        public IActionResult Add(SignUpViewModel vm)
        {
            if (ModelState.IsValid)
            {
                User newUser = new User
                {
                    Email = vm.Email,
                    Username = vm.Username,
                    Password = vm.Password,
                };
                return Redirect("/Hello/Index");
            }
            return View(vm);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Order/Add.cshtml
@model TRPTools.ViewModels.AddOrderViewModel

<form asp-for="Order" asp-action="Add" formmethod="post">
    <div class="form-group">
        <label asp-for="CupType"></label>
        <select class="form-control" asp-for="CupType" />
    </div>
    <label asp-for="Glitter"></label>
    <div class="form-group">
        <select class="form-control" asp-for="Glitter" />
    </div>
    <input type="submit" value="Submit" />
</form>

Views/Order/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TRPTools</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TRPTools</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TRPTools - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/SignUp/Add.cshtml
@model TRPTools.ViewModels.SignUpViewModel

    <form asp-for="Username" asp-action="Add" formmethod="post">
        <div class="form-group">
            <label asp-for="Email"></label>
            <input class="form-control" asp-for="Email"/>
            <span asp-validation-for="Email"></span>
        </div>
        <label asp-for="Username"></label>
            <div class="form-group">
                <input class="form-control" asp-for="Username" />
                <span asp-validation-for="Username"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password"></label>
                <input class="form-control" asp-for="Password" />
                <span asp-validation-for="Password"></span>
            </div>
            <div class="form-group">
                <label asp-for="Verify"></label>
                <input class="form-control" asp-for="Verify"/>
                <span asp-validation-for="Verify"></span>
            </div>
            <input type="submit" value="Submit" />
    </form>

Views/SignUp/Index.cshtml
<p><a asp-controller="SignUp" asp-action="Add">SignUp</a></p>